# Generated by Django 5.2.1 on 2026-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lun',
            name='svm_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
