# Generated by Django 5.2.11 on 2026-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0002_lun_svm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lun',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quota',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
