# Generated by Django 5.2.11 on 2026-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0003_lun_uuid_quota_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='uuid',
            new_name='volume_uuid',
        ),
        migrations.AddField(
            model_name='quota',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
