# Generated by Django 5.2.11 on 2026-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0004_rename_uuid_quota_volume_uuid_quota_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
