# Generated by Django 5.2.11 on 2026-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0005_alter_quota_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='qtree_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
