# SPDX-FileCopyrightText: 2026 Gabor Somogyvari, Leonhard Kreißig (Deutsche Telekom AG) <leonhard.kreissig@telekom.de>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 5.2.1 on 2026-03-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ontap', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('svm', 'name')},
        ),
    ]
